<?php

$docs = 'README* CHANGELOG* ChangeLog* FAQ* CONTRIBUTING* HISTORY* UPGRADING* UPGRADE* package* demo example examples doc docs readme*';
$tests = '.travis.yml .scrutinizer.yml phpunit.xml* phpunit.php test tests Test Tests';
$standard = "{$docs} {$tests}";

return [
    'dir'   => base_path() . '/vendor',
    'rules' => [

    // Common packages
        'anahkiasen/former'                     => "{$standard}",
        'anahkiasen/html-object'                => "{$docs} phpunit.xml* tests/*",
        'anahkiasen/underscore-php'             => "{$standard}",
        'anahkiasen/rocketeer'                  => "{$standard}",
        'barryvdh/laravel-debugbar'             => "{$standard}",
        'bllim/datatables'                      => "{$standard}",
        'cartalyst/sentry'                      => "{$standard}",
        'dflydev/markdown'                      => "{$standard}",
        'doctrine/annotations'                  => "{$standard} bin",
        'doctrine/cache'                        => "{$standard} bin",
        'doctrine/collections'                  => "{$standard}",
        'doctrine/common'                       => "{$standard} bin lib/vendor",
        'doctrine/dbal'                         => "{$standard} bin build* docs2 lib/vendor",
        'doctrine/inflector'                    => "{$standard}",
        'dompdf/dompdf'                         => "{$standard} www",
        'guzzle/guzzle'                         => "{$standard}",
        'guzzlehttp/guzzle'                     => "{$standard}",
        'guzzlehttp/oauth-subscriber'           => "{$standard}",
        'guzzlehttp/streams'                    => "{$standard}",
        'imagine/imagine'                       => "{$standard} lib/Imagine/Test",
        'intervention/image'                    => "{$standard} public",
        'jasonlewis/basset'                     => "{$standard}",
        'jeremeamia/SuperClosure'               => "{$standard} demo",
        'kriswallsmith/assetic'                 => "{$standard}",
        'leafo/lessphp'                         => "{$standard} Makefile package.sh",
        'league/stack-robots'                   => "{$standard}",
        'maximebf/debugbar'                     => "{$standard} demo",
        'mockery/mockery'                       => "{$standard}",
        'mrclay/minify'                         => "{$standard} MIN.txt min_extras min_unit_tests min/builder min/config* min/quick-test* min/utils.php min/groupsConfig.php min/index.php",
        'mustache/mustache'                     => "{$standard} bin",
        'oyejorge/less.php'                     => "{$standard}",
        'phenx/php-font-lib'                    => "{$standard} www",
        'phpdocumentor/reflection-docblock'     => "{$standard}",
        'phpoffice/phpexcel'                    => "{$standard} Examples unitTests changelog.txt",
        'rcrowe/twigbridge'                     => "{$standard}",
        'tijsverkoyen/css-to-inline-styles'     => "{$standard}",
        'twig/twig'                             => "{$standard}",
        'venturecraft/revisionable'             => "{$standard}",
        'willdurand/geocoder'                   => "{$standard}",

        /**
         * Default Laravel 5.0 Packages
         */
        'danielstjules/stringy'                                     => "{$standard}",
        'dnoegel/php-xdg-base-dir'                                  => "{$standard}",
        'doctrine/inflector'                                        => "{$standard}",
        'doctrine/instantiator'                                     => "{$standard}",
        'ircmaxell'                                                 => 'version-test.php',
        'jakub-onderka/php-console-color'                           => "{$standard}",
        'jakub-onderka/php-console-highlighter'                     => "{$standard}",
        'jeremeamia/SuperClosure'                                   => "{$standard}",
        'league/flysystem'                                          => "{$standard}",
        'monolog/monolog'                                           => "{$standard} .php_cs",
        'mtdowling/cron-expression'                                 => "{$standard} .editorconfig",
        'nesbot/carbon'                                             => "{$standard} .php_cs.dist",
        'nikic/php-parser'                                          => "{$standard} test_old UPGRADE-1.0.md",
        'paragonie/random_compat'                                   => "{$standard}",
        'phpdocumentor/reflection-common'                           => "{$standard}",
        'phpdocumentor/reflection-docblock'                         => "{$standard}",
        'phpdocumentor/type-resolver'                               => "{$standard}",
        'phpspec/php-diff'                                          => "{$standard}",
        'phpspec/phpspec'                                           => "{$standard} .phpspec",
        'phpspec/prophecy'                                          => "{$standard}",
        'phpunit/php-code-coverage'                                 => "{$standard}",
        'phpunit/php-file-iterator'                                 => "{$standard}",
        'phpunit/php-text-template'                                 => "{$standard}",
        'phpunit/php-timer'                                         => "{$standard}",
        'phpunit/php-token-stream'                                  => "{$standard}",
        'phpunit/phpunit'                                           => "{$standard} .php_cs",
        'phpunit/phpunit-mock-objects'                              => "{$standard}",
        'psr/log/Psr/Log'                                           => "{$standard}",
        'psy/psysh'                                                 => "{$standard}",
        'sebastian/comparator'                                      => "{$standard}",
        'sebastian/diff'                                            => "{$standard} .php_cs",
        'sebastian/environment'                                     => "{$standard}",
        'sebastian/exporter'                                        => "{$standard}",
        'sebastian/global-state'                                    => "{$standard}",
        'sebastian/recursion-context'                               => "{$standard}",
        'sebastian/version'                                         => "{$standard}",
        'swiftmailer/swiftmailer'                                   => "{$standard} .php_cs.dist",
        'symfony/console/Symfony/Component/Console'                 => "{$standard} Tester",
        'symfony/debug/Symfony/Component/Debug'                     => "{$standard}",
        'symfony/event-dispatcher'                                  => "{$standard}",
        'symfony/filesystem'                                        => "{$standard}",
        'symfony/finder/Symfony/Component/Finder'                   => "{$standard}",
        'symfony/http-foundation/Symfony/Component/HttpFoundation'  => "{$standard}",
        'symfony/http-kernel/Symfony/Component/HttpKernel'          => "{$standard}",
        'symfony/process/Symfony/Component/Process'                 => "{$standard}",
        'symfony/routing/Symfony/Component/Routing'                 => "{$standard}",
        'symfony/security-core/Symfony/Component/Security/Core'     => "{$standard}",
        'symfony/translation/Symfony/Component/Translation'         => "{$standard}",
        'symfony/var-dumper/Symfony/Component/VarDumper'            => "{$standard}",
        'symfony/yaml'                                              => "{$standard}",
        'webmozart/assert'                                          => "{$standard}",

        /**
         * Laravel 5.1 Additional Packages
         */
        'fzaninotto/faker'              => "{$standard} Makefile",
        'hamcrest/hamcrest-php'         => "{$standard} .coveralls.yml .gush.yml TODO.txt",
        'mockery/mockery'               => "{$standard} travis .styleci.yml",
        'symfony/css-selector'          => "{$standard}",
        'symfony/dom-crawler'           => "{$standard}",
    ]
];
